version: '3'

services:
  e-commerce-pg:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=ecommerce